# ---------------- Hyprlock ---------------- >

# -------- Wallpaper -------- >

background {

    monitor =

    path = ~/.config/hyprpaper/wallpapers/storm.jpg # Your wallpaper path

    blur_passes = 2
    blur_size   = 7

    noise      = 0.0117
    contrast   = 0.8916
    brightness = 0.8172
    vibrancy   = 0.1696
    
}

# -------- Clock -------- >

label {

    monitor =

    text = cmd[update:1000] echo "$(date +"%H:%M")"

    color = rgba(235, 235, 235, 0.95)

    font_size   = 120
    font_weight = ExtraBold
    font_family = JetBrainsMono Nerd Font

    position = 0, 240

    halign = center
    valign = center

}

# -------- Date -------- >

label {

    monitor =

    text = cmd[update:1000] echo "$(date +"%A, %d %B")"

    color = rgba(210, 210, 210, 0.85)

    font_size  = 24
    font_family = JetBrainsMono Nerd Font

    position = 0, 140

    halign = center
    valign = center

}

# -------- Profile -------- >

image {

    monitor =

    path = ~/.config/hypr/images/user.jpg # Your profile picture path

    size = 140

    rounding     = -1
    border_size  = 3
    border_color = rgba(255, 255, 255, 0.25)

    position = 0, -10

    halign = center
    valign = center

}

# -------- User -------- >

label {

    monitor =

    text = Hi, $USER # Your username

    color = rgba(235, 235, 235, 0.85)

    font_size   = 16
    font_family = JetBrainsMono Nerd Font

    position = 0, -130

    halign = center
    valign = center

}

# -------- Input -------- >

input-field {

    monitor =

    size = 300, 45

    outline_thickness = 1

    dots_size    = 0.3
    dots_spacing = 0.15
    dots_center  = true

    outer_color = rgba(255, 255, 255, 0.15)
    inner_color = rgba(255, 255, 255, 0.08)
    font_color  = rgba(235, 235, 235, 0.95)

    fade_on_empty = false

    placeholder_text = <i>Enter Pass</i>

    position = 0, -190

    halign = center
    valign = center

}